cicd: deploy.yml 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,47 +18,27 @@ jobs:
                   docker build -f ./docker/Dockerfile -t taewan2002/docent-front .
                   docker push taewan2002/docent-front
 
-            - name: Prune directory 'Docent-Front'
+            - name: Deploy
               uses: appleboy/ssh-action@master
               with:
                   host: ${{ secrets.NCP_HOST }}
                   username: ${{ secrets.NCP_USER }}
                   password: ${{ secrets.NCP_PASSWORD }}
                   key: ${{ secrets.NCP_KEY }}
+                  envs: GITHUB_SHA
                   script: |
-                      rm -rf /Docent-Front/docker
-                      mkdir /Docent-Front/docker
+                      # Pull the new image
+                      sudo docker pull taewan2002/docent-front
 
-            - name: Copy file
-              uses: appleboy/scp-action@master
-              with:
-                  host: ${{ secrets.NCP_HOST }}
-                  username: ${{ secrets.NCP_USER }}
-                  key: ${{ secrets.NCP_KEY }}
-                  password: ${{ secrets.NCP_PASSWORD }}
-                  port: 22
-                  source: "./docker/"
-                  target: "/Docent-Front/docker"
+                      # Stop & Start
+                      echo "✔️ Docker Stop & Start"
+                      sudo docker stop docent-front
+                      sudo docker run -d --name docent-front -p 3000:3000 taewan2002/docent-front
 
-            # - name: Deploy
-            #   uses: appleboy/ssh-action@master
-            #   with:
-            #       host: ${{ secrets.NCP_HOST }}
-            #       username: ${{ secrets.NCP_USER }}
-            #       password: ${{ secrets.NCP_PASSWORD }}
-            #       key: ${{ secrets.NCP_KEY }}
-            #       envs: GITHUB_SHA
-            #       script: |
-            #           # Pull the new image
-            #           sudo docker pull taewan2002/docent-front
+                      # Check
+                      echo "✔️ Docker ps"
+                      docker ps
 
-            #           # Stop & Start
-            #            sudo docker-compose -f /Docent-front/docker/docker-compose.yml down
-            #           sudo docker-compose -f /Docent-front/docker/docker-compose.yml up -d
-
-            #           # Check
-            #           docker ps
-
-            #           # Cleanup old images
-            #           echo "🧹 Cleaning up old Docker images"
-            #           sudo docker rmi -f $(sudo docker images -q) || true
+                      # Cleanup old images
+                      echo "🧹 Cleaning up old Docker images"
+                      sudo docker rmi -f $(sudo docker images -q) || true
